# Generated by Django 5.2.12 on 2026-07-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0002_alter_hospital_latitude_alter_hospital_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='icu_beds',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_beds',
            field=models.CharField(blank=True, null=True),
        ),
    ]
