# Generated by Django 5.2.12 on 2026-07-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0003_alter_hospital_icu_beds_alter_hospital_total_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='icu_beds',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_beds',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
