# Generated by Django 5.2.12 on 2026-07-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0004_alter_hospital_icu_beds_alter_hospital_total_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=10),
        ),
    ]
