# Generated by Django 5.2.12 on 2026-07-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0008_fieldworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldworker',
            name='department',
            field=models.CharField(choices=[('Disease Surveillance', 'Disease Surveillance'), ('Public Health', 'Public Health'), ('Immunization', 'Immunization'), ('Emergency Response', 'Emergency Response'), ('Health Education', 'Health Education')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fieldworker',
            name='designation',
            field=models.CharField(choices=[('Health Inspector', 'Health Inspector'), ('Junior Health Inspector', 'Junior Health Inspector'), ('Public Health Nurse', 'Public Health Nurse'), ('Field Investigator', 'Field Investigator'), ('Community Health Worker', 'Community Health Worker')], max_length=100),
        ),
        migrations.AlterField(
            model_name='fieldworker',
            name='district',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldworker',
            name='employee_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='fieldworker',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fieldworker',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fieldworker',
            name='ward',
            field=models.CharField(max_length=30),
        ),
    ]
