# Generated by Django 5.1.6 on 2026-07-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0009_alter_fieldworker_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('alert_type', models.CharField(choices=[('Disease', 'Disease'), ('Weather', 'Weather'), ('Emergency', 'Emergency'), ('General', 'General')], max_length=20)),
                ('description', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Healthcare_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=30)),
                ('driver_name', models.CharField(max_length=100)),
                ('assigned_date', models.DateField()),
                ('remarks', models.TextField()),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Assigned', max_length=20)),
                ('field_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.fieldworker')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.region')),
            ],
        ),
    ]
