# Generated by Django 5.1.6 on 2026-07-27 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0010_healthalert_mobile_healthcare_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCaseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_count', models.PositiveIntegerField()),
                ('male_cases', models.PositiveIntegerField(default=0)),
                ('female_cases', models.PositiveIntegerField(default=0)),
                ('children_cases', models.PositiveIntegerField(default=0)),
                ('report_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.disease')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.hospital')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.region')),
            ],
        ),
    ]
