# Generated by Django 5.1.6 on 2026-07-29 16:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0011_diseasecasereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccinationCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=150)),
                ('camp_date', models.DateField()),
                ('camp_time', models.TimeField()),
                ('venue', models.CharField(max_length=250)),
                ('target_population', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.disease')),
                ('field_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.fieldworker')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.hospital')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.region')),
            ],
        ),
    ]
