# Generated by Django 5.2.14 on 2026-07-30 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0012_vaccinationcampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampCompletionReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_people', models.PositiveIntegerField()),
                ('vaccinated_people', models.PositiveIntegerField()),
                ('health_checkups', models.PositiveIntegerField()),
                ('medicines_distributed', models.PositiveIntegerField()),
                ('remarks', models.TextField()),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.vaccinationcampaign')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.fieldworker')),
            ],
        ),
    ]
