# Generated by Django 5.2.14 on 2026-07-30 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0013_campcompletionreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthalert',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.region'),
        ),
    ]
