# Generated by Django 5.1.6 on 2026-07-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0015_auto_20260730_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldworker',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HelathApp.region'),
        ),
    ]
