# Generated by Django 5.1.6 on 2026-07-30 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0016_fieldworker_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField()),
                ('total_houses', models.PositiveIntegerField()),
                ('houses_visited', models.PositiveIntegerField()),
                ('total_population', models.PositiveIntegerField()),
                ('male_population', models.PositiveIntegerField()),
                ('female_population', models.PositiveIntegerField()),
                ('children', models.PositiveIntegerField()),
                ('senior_citizens', models.PositiveIntegerField()),
                ('pregnant_women', models.PositiveIntegerField()),
                ('disabled_people', models.PositiveIntegerField()),
                ('vaccinated_people', models.PositiveIntegerField()),
                ('unvaccinated_people', models.PositiveIntegerField()),
                ('chronic_patients', models.PositiveIntegerField()),
                ('fever_cases', models.PositiveIntegerField(default=0)),
                ('suspected_dengue', models.PositiveIntegerField(default=0)),
                ('suspected_malaria', models.PositiveIntegerField(default=0)),
                ('water_sources_checked', models.PositiveIntegerField(default=0)),
                ('unsafe_water_sources', models.PositiveIntegerField(default=0)),
                ('sanitation_issues', models.PositiveIntegerField(default=0)),
                ('awareness_programs', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.region')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.fieldworker')),
            ],
        ),
    ]
