# Generated by Django 5.2.14 on 2026-07-31 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0017_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('predicted_cases', models.FloatField()),
                ('lower_confidence', models.FloatField()),
                ('upper_confidence', models.FloatField()),
                ('model_name', models.CharField(default='ARIMA', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.disease')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HelathApp.region')),
            ],
        ),
    ]
