# Generated by Django 5.1.6 on 2026-08-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelathApp', '0019_diseaseprediction_prediction_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='precautions',
            field=models.TextField(blank=True),
        ),
    ]
